openapi: 3.1.0
info:
  version: 1.0.0
  title: Aqua Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Add and save your consumed water, control your daily water rate
tags:
  - name: Water
    description: Operations about consumed water
  - name: Users
    description: Operations about users
  - name: Auth
    description: Auth operations
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-okzz #посилання на задеплоєний сайт
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/day:
    get:
      $ref: ../swagger/paths/water/getForDay.yaml
  /water/month:
    $ref: ../swagger/paths/water/getForMonth.yaml
  /water/{waterId}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
